[package]
name = "set-game-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1.9.0"
pretty_assertions = "1.1.0"
rand = "0.8.5"
rand_pcg = "0.3.1"

[dev-dependencies]
itertools = "0.10.3"
